
# Visualizing Seurat objects


```{r pbmc-create}
library(Seurat)
dir = "data/filtered_gene_bc_matrices/hg19"

pbmc.data <- Read10X(data.dir = dir)
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", 
                          min.cells=3, min.features=200)
pbmc
```

```{r pbmc-qc}
pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")
pbmc <- subset(pbmc,
  subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5
)
```

```{r pbmc-normalize}
pbmc <- NormalizeData(pbmc, normalization.method = "LogNormalize",
                      scale.factor = 10000)
pbmc <- ScaleData(pbmc)
```

```{r pbmc-dimension-reduction}
pbmc <- FindVariableFeatures(pbmc, selection.method = "vst",
                             nfeatures = 2000)
pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))
pbmc <- RunUMAP(pbmc, dims = 1:10)
```

```{r pbmc-clusters}
pbmc <- FindNeighbors(pbmc, dims = 1:10)
pbmc <- FindClusters(pbmc, resolution = 0.5)

## Assigning cell type identity to clusters
cluster.ids <- c("Naive CD4 T", "CD14+ Mono", "Memory CD4 T", 
            "B", "CD8 T", "FCGR3A+ Mono", "NK", "DC", "Platelet")
names(cluster.ids) <- levels(pbmc)
pbmc <- RenameIdents(pbmc, cluster.ids)
```

## Dimensional reduction plot

```{r dimplot, fig.width=9, fig.height=6}
# DimPlot(pbmc, reduction = "umap",
#        label = TRUE, pt.size = 0.5) 

library(ggplot2)
library(ggsc)

sc_dim(pbmc) + sc_dim_geom_label()


sc_dim(pbmc) + 
    sc_dim_geom_label(geom = shadowtext::geom_shadowtext, 
            color='black', bg.color='white')
```

## Visualize 'features' on a dimensional reduction plot

```{r feature-plot}
features = c("MS4A1", "GNLY", "CD3E", 
            "CD14", "FCER1A", "FCGR3A", 
            "LYZ", "PPBP", "CD8A")

# FeaturePlot(pbmc,'CD4')
sc_feature(pbmc, 'CD4')
```


```{r feature-plot-multi}
sc_feature(pbmc, features)
```


Here is the real 'features' on dimensional plot


```{r dim-feature}
sc_dim(pbmc) + 
   sc_dim_geom_feature(pbmc, 'CD4', color='black')

sc_dim(pbmc, alpha=.3) + 
    ggnewscale::new_scale_color() + 
    sc_dim_geom_feature(pbmc, features, mapping=aes(color=features)) +
    scale_color_viridis_d()

sc_dim(pbmc) +
    sc_dim_geom_feature(pbmc, 'CD4', color='black')

sc_dim(pbmc, alpha=.3) +
    ggnewscale::new_scale_color() +
    sc_dim_geom_feature(pbmc, features, mapping=aes(color=features)) +
    scale_color_viridis_d()
```

## Visualize ellipse on a dimensional reduction plot

```{r dim-ellipse}
sc_dim(pbmc) +
  sc_dim_geom_ellipse(level=0.95)
```

## Visualize selected clusters 

```{r dim-sub}
selected <- c("Naive CD4 T", "NK")
sc_dim(pbmc) + 
  sc_dim_sub(subset=selected)
```

```{r dim-sub-label}
sc_dim(pbmc, color='grey') + 
  sc_dim_geom_sub(subset=selected) + 
    sc_dim_geom_label(geom = shadowtext::geom_shadowtext, 
          mapping = aes(subset = ident %in% selected),
            color='black', bg.color='white')
```

<!-- 
## Dot plot

``` r eval=FALSE
DotPlot(pbmc, features = c("MS4A1", "GNLY", "CD3E", 
                           "CD14", "FCER1A", "FCGR3A", 
                           "LYZ", "PPBP", "CD8A"),
        group.by = 'seurat_clusters')
```        

-->


## Violin plot of gene expression

```{r sc-violin}
# VlnPlot(pbmc,'CD4')

sc_violin(pbmc, 'CD4')

## allows applying an user-defined function to transform/filter the data
sc_violin(pbmc, 'CD4', .fun=function(d) dplyr::filter(d, value > 0)) +
  ggforce::geom_sina(size=.1)
```

```{r sc-violin-multi, fig.height=9}
#VlnPlot(pbmc, features)
sc_violin(pbmc, features) + 
  theme(axis.text.x = element_text(angle=45, hjust=1))
```



## Spatial features

```{r sc_spatial}
library(SeuratData)
# InstallData("stxBrain")
brain <- LoadData("stxBrain", type = "anterior1")
# Normalization 
brain <- SCTransform(brain, assay = "Spatial", verbose = FALSE)

## SpatialFeaturePlot(brain, features = c("Hpca", "Ttr"))\
sc_spatial(brain, features = c("Hpca", "Ttr"), image.mirror.axis = 'v')
```

